apiVersion: v1
kind: Service
metadata:
  name: {{ include "jumbleapi.fullname" . }}
  labels:
    {{- include "jumbleapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.jumbleapi.service.type }}
  ports:
    - port: 8000
      targetPort: {{ .Values.jumbleapi.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "jumbleapi.selectorLabels" . | nindent 4 }}
